---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-example-config
  namespace: capi-self
data:
  values.yaml: |
    # Must match the name of the (sealed) secret in credentials.yaml
    cloudCredentialsSecretName: cluster-dawntest-credentials

    kubernetesVersion: 1.31.4
    machineImageId: "6ed3da4b-3b65-4d44-959f-f35956db1c78"

    clusterNetworking:
      externalNetworkId: "4d00778c-303f-49b2-b624-e3004262312d"
      internalNetwork:
        networkFilter:
          id: 5ee983c5-12b2-4bf4-83c6-e7cb394801e0
          name: bm-test-net

    controlPlane:
      machineFlavor: "vm.v1.small"
      machineCount: 3

    nodeGroups:
      - name: vm
        machineFlavor: "vm.v1.small"
        machineCount: 3
      - name: baremetal
        machineFlavor: "bm.c6420.p8276.m192"
        machineCount: 1

    addons:
      cni:
        type: cilium
        cilium:
          release:
            values:
              hubble:
                relay:
                  enabled: true
                ui:
                  enabled: true
      monitoring:
        enabled: true
      openstack:
        enabled: true
        # csiManila:
        #   enabled: true
      nodeFeatureDiscovery:
        enabled: true
      nvidiaGPUOperator:
        enabled: false
      mellanoxNetworkOperator:
        enabled: true
      ingress:
        enabled: true
        nginx:
          release:
            values:
              controller:
                extraArgs:
                  enable-ssl-passthrough: "true"
