---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-example-config
  namespace: capi-self
data:
  values.yaml: |
    # Must match the name of the (sealed) secret in credentials.yaml
    cloudCredentialsSecretName: cluster-example-credentials

    kubernetesVersion: 1.30.0
    machineImageId: "<image id>"

    clusterNetworking:
      externalNetworkId: "<external net id>"

    controlPlane:
      machineFlavor: "<flavor id>"
      machineCount: 3

    nodeGroups:
      - name: md-0
        machineFlavor: "<flavor id>"
        machineCount: 3

    addons:
      # Use the cilium CNI
      cni:
        type: cilium

      # Enable the monitoring stack
      monitoring:
        enabled: true

      # Disable NFD and the NVIDIA/Mellanox operators
      nodeFeatureDiscovery:
        enabled: false
      nvidiaGPUOperator:
        enabled: false
      mellanoxNetworkOperator:
        enabled: false
